name: CI Bisect 5

on:
  workflow_dispatch:
    inputs:
      run_e2e:
        description: 'Run E2E (set to 1 to run)'
        required: false
        default: '0'
  push:
    branches: [ chore/db-backup-tests, chore/clean-workflows ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print test
        run: echo "bisect5 test"

  e2e:
    if: ${{ github.event.inputs.run_e2e == '1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print e2e
        run: echo "bisect5 e2e"

