name: CI Bisect 5

on:
  workflow_dispatch: {}
  push:
    branches: [ chore/db-backup-tests, chore/clean-workflows ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print test
        run: echo "bisect5 test"

