name: CI Bisect 2

on:
  workflow_dispatch: {}
  push:
    branches: [ chore/db-backup-tests, chore/clean-workflows ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print
        run: |
          echo "bisect2: OK python ${{ matrix.python-version }}"
