name: CI Bisect 1

on:
  workflow_dispatch: {}
  push:
    branches: [ chore/clean-workflows, chore/db-backup-tests ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print
        run: |
          echo "bisect1: OK"
