name: CI Bisect 5 Fixed

on:
  workflow_dispatch: {}
  push:
    branches: [ chore/db-backup-tests ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print test
        run: echo "bisect5 fixed test"

  e2e:
    if: ${{ env.RUN_E2E == '1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print e2e
        run: echo "bisect5 fixed e2e"
