name: CI Clean Test

on:
  workflow_dispatch: {}
  push:
    branches: [ chore/clean-workflows ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print
        run: echo "ci-clean: OK"
