name: CI Debug

on:
  workflow_dispatch: {}
  push:
    branches: [ chore/db-backup-tests, chore/clean-workflows ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print debug info
        run: |
          echo "CI debug: hello from $GITHUB_ACTOR"
          uname -a
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
name: CI Debug

on:
  workflow_dispatch: {}
  push:
    branches: [ chore/db-backup-tests ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print debug info
        run: |
          echo "CI debug: hello from $GITHUB_ACTOR"
          uname -a
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
