name: CI

on:
  push:
    branches: [ main, chore/db-backup-tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        mode: [fast, full]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r doc_processor/requirements.txt
      - name: Run tests (fast vs full)
        run: |
          if [ "${{ matrix.mode }}" = "fast" ]; then
            pytest -q -k "not slow";
          else
            pytest -q;
          fi

  e2e:
    # Keep E2E separate; only run manually or when E2E=1 is set
    if: ${{ env.RUN_E2E == '1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r doc_processor/requirements.txt
          pip install playwright pytest-playwright
          playwright install --with-deps
      - name: Start app
        run: |
          ./start_app.sh &
          sleep 3
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_E2E: '1'
        run: |
          pytest -q doc_processor/tests/test_e2e_scaffold_playwright.py -q -s
