name: Validate Smoke Dispatch

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manual trigger to force registration'
        required: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "validate-smoke-dispatch: OK"
